### PR TITLE
Don't assume about the virtual env dir name

### PR DESCRIPTION
**Pull request by nkakouros**

### CODE REVIEW

**Comment by nkakouros** [comment]
Actually, mypy ignores files/dirs starting with `.`. So why not install your venv under .venv?

**Review by mrkickling — APPROVED** [review]
Makes sense, feel free to merge

**Comment by nkakouros** [comment]
Actually, I will make some further edits.

**Comment by andrewbwm** [comment]
> Actually, I will make some further edits.

@nkakouros what is going on with this pull request? Is it still relevant? Is still being worked on? Did the intervening changes make it obsolete or require an update?

**Comment by nkakouros** [comment]
I don't remember. There was a better way to handle some things, but I am not sure anymore. Given that the checks pass and in particular that the mypy check finds and checks all files, I would merge this to avoid virtualenv folders from being picked up by mypy.

**Comment by andrewbwm** [comment]
Was squashed into 2df9b74a77a60206ae631ca368080bfb96f5f86b.

**Pull request closed without merging**
